# -*- coding: utf-8 -*-
"""DAY5_neuralnetwork.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EnsZlR_eRkk-sdo60SAwwhxnUeDgArB8
"""

import streamlit as st
import numpy as np
from PIL import Image
import tensorflow as tf
from tensorflow.keras.models import load_model

# Page Configuration
st.set_page_config(
    page_title="Gender Classification",
    page_icon="🧠",
    layout="centered"
)

# Load Model
@st.cache_resource
def load_my_model():
    return load_model("binary_image_classifier.h5")

model = load_my_model()

# Title
st.title("🧠 Gender Classification using CNN")
st.write("Upload an image to predict whether the person is Male or Female.")

# Upload Image
uploaded_file = st.file_uploader(
    "Choose an Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    image = Image.open(uploaded_file)

    st.image(image, caption="Uploaded Image", use_container_width=True)

    # Resize
    image = image.resize((150,150))

    # Convert to Array
    img_array = np.array(image)

    # Handle grayscale image
    if len(img_array.shape) == 2:
        img_array = np.stack((img_array,)*3, axis=-1)

    img_array = img_array / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    if st.button("Predict"):

        prediction = model.predict(img_array)

        confidence = float(prediction[0][0])

        if confidence >= 0.5:
            st.success("Prediction : Female 👩")
        else:
            st.success("Prediction : Male 👨")

        st.write(f"Confidence Score : {confidence:.4f}")

